### PR TITLE
Unit testing for VM programs

### PR DESCRIPTION
**Pull request by ducky64**
Depends on #228, fast-forward scheduler.

Adds an end-to-end test for the VM using the JDOM unit test utilities (#225) and with the button servo example program. It seems to work!

I'm not perfectly happy with how this looks, but this seems like a usable way to write unit tests for VM programs. The VM-program-specific harness construction is broken into a `withHarness` wrapper function, so each test case only contains the scenario code (without duplicating the bus and role manager setup).

Things that needs more thought:
- The `testBody` function signature (to `withHarness`) is pretty verbose. Part of it is the `CreatedServerService` wrappers everywhere, and part of it is that it needs each server. One alternative might be to make these global variables that are initialized on a setup / teardown, though you end up with a lot of `let`s instead of function arguments.
- (Implemented) ~The roles consumes a lot of lines of code without providing any new information - really all it needs is a name and service.~
- Ideally we'd be able to infer servers from the VM program and spin them up automatically, but:
  - It's nice to have a typed `*Server` handle, so barring codegen approaches I don't think there's an approach where the user doesn't declare each server individually at some point.
  - There probably isn't a 1:1 mapping of a `*Server` class to the serviceClass, so automatic inference might be difficult 
- (Implemented) ~But there might be a compromise solution for the two above point, a test helper that binds services to VM roles. It would be more than a macro around RoleManager.setRoles by checking for completeness against the VMProgram's requirements.~ Implemented

"Future work" (in another PR):
- Ideally we could load the blockly JSONs / XMLs directly, with compilation happening as part of the unit test (instead of needing to manually generate the VMProgram JSON from a blockly JSON / XML. This could be a test helper function.

---

Also, for whatever reason src/vm/compile.ts requires a modification or the TypeScript compiler vomits (type error! 🤪) locally for me. This code is tested against that change, but that change isn't part of this PR because I'm not sure of the ramifications, and it appears it's not breaking the build

```diff
diff --git a/src/vm/compile.ts b/src/vm/compile.ts
index 30e1105a..7a0862a3 100644
--- a/src/vm/compile.ts
+++ b/src/vm/compile.ts
@@ -188,10 +188,10 @@ export const getServiceFromRole = (info: VMProgram) => (role: string) => {
             roleFound.serviceClass
         )
         assert(!!spec, `service class ${roleFound.serviceClass} not resolved`)
-        return { spec, client }
+        return spec
     } else {
         const spec = serviceSpecificationFromName(role)
-        return { spec, client: true }
+        return spec
     }
 }
```

### CODE REVIEW

**Comment by pelikhan** [comment]
compile.ts stuff needs to be checked with @microsoft/jacdac-collaborators

**Review by pelikhan — APPROVED** [review]
Next food for tought: it is possible to use this with the TestDSL in jacdac-docs so that one can write unit tests **within** the VM program in the bloc editor?

**Comment by ducky64** [comment]
So I think the TestDSL has interactive human input aspects, which isn't a great fit for a regression suite. The tests here are pure simulation.

That being said, I can certainly see how an interactive test system might be useful as a compatibility test suite, though probably aimed more for development and order one to tens of units instead of factory-level QA. I think part of that project might just be building a (web?) GUI around some of the bus test primitives here and adding interactivity primitives. Would probably be more intended for test running - for a compatibility test suite I'm not sure about the bang-for-the-buck for building a blocks test-writing interface.

**Comment by ducky64** [comment]
Merging now so I can write more tests for more VM programs against this. It's not perfect yet, but more test cases should drive development.

**Comment by ducky64** [comment]
Also resolved the compiler.ts issue, looks like an out-of-date submodule

**Pull request merged**
